### ISSUE TITLE
CMake / Linux support

### ISSUE THREAD

**Issue by abasgames** [ScriptedSnark/SvenBXT#2]
would svenBXT add support for compiling it with cmake under linux

**Comment by ScriptedSnark** [comment]
SvenBXT temporarily unsupported for Linux operating systems.
About CMake, it will be added in future commits

**Comment by ScriptedSnark** [comment]
> would svenBXT add support for compiling it with cmake under linux

Rewriting SvenBXT from scratch. Now it supports Linux/CMake. Available in branch `new`.
