### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by sh0tx420** [ScriptedSnark/SvenBXT#3]
Some features would be nice to implement from the original BXT:
- Autobhopping and ducktap bind (+bxt_tas_autojump or bxt_autojump 0/1, +bxt_tas_ducktap)
- CVar to enable or disable bhop cap
- Nihilanth HUD

Autobhopping is (probably) forbidden in official Sven Co-op runs, but it would still be good to implement for players like me who speedrun the game for fun

**Comment by ScriptedSnark** [comment]
>     * Autobhopping and ducktap bind (+bxt_tas_autojump or bxt_autojump 0/1, +bxt_tas_ducktap)

It can be added after demo buffer implementation.

>     * CVar to enable or disable bhop cap

Is there a bhop cap in Sven Co-op? 😳

>     * Nihilanth HUD

Also will be implemented after demo buffer implementation
Nihilanth HUD is possible only for host.

**Comment by sh0tx420** [comment]
> Is there a bhop cap in Sven Co-op?

Probably not, but BXT has a CVar to enable or disable it, although now that i think twice about it, it's probably useless :D
