### ISSUE TITLE
no .exe file

### ISSUE THREAD

**Issue by queoene** [ScriptedSnark/SvenBXT#4]
no .exe file, what to do?

**Comment by WhyiMicro** [comment]
there is literally a `.dll` and a `.exe` injector in the download:
https://github.com/ScriptedSnark/SvenBXT/releases/download/nov-26-2022/SvenBXT-Rebased.zip

**Comment by ScriptedSnark** [comment]
> no .exe file, what to do?

There is EXE file. I think your antivirus deleted it.
